spring.application.name=ArCash

spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

spring.jwt.secret=IifnN6jIw9KHO/Az16szIgxzo5e4TZB2hr3Bg2JHfGc=
spring.mail.username=test@email.com
spring.mail.password=testpass
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.host=smtp.gmail.com
spring.mail.port=587

server.port=8081





