spring.application.name=ArCash
server.port=${PORT:8080}

# === CAMBIO AQU� ===
# Lee la variable de entorno "APP_FRONTEND_URL".
# Si no existe, usa "https://arcash.me" como valor por defecto.
app.frontend.url=${APP_FRONTEND_URL:https://arcash.me}
# === FIN DEL CAMBIO ===

app.dolar.api.url=${DOLAR_API_URL:https://dolarapi.com/v1/dolares/oficial}
app.cards.crypto-secret=${CARDS_CRYPTO_SECRET:arcash-dev-cards-secret-change-me}

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASS:root}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jwt.secret=${SIGNED_JWT}
spring.mail.password=${RESEND_API_KEY}
